[package]
name = "sinking-fund"
version = "0.1.0"
authors = ["Ethan Kent <ekent@jd11.law.harvard.edu>"]
edition = "2018"

[dependencies]
diesel = { version = "1.4.3", features = ["postgres", "chrono"] }
dotenv = "0.14"
chrono = "0.4.9"
juniper = "0.11"
